# Generated by Django 4.0.5 on 2022-06-05 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_category_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.category'),
        ),
    ]
