# Generated by Django 4.0.5 on 2022-06-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_alter_clothing_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='url',
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='clothing',
            name='img',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='clothing',
            name='sku',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='clothing',
            name='url',
            field=models.URLField(default=None),
        ),
    ]
