# Generated by Django 4.0.5 on 2022-06-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0006_remove_category_url_remove_clothing_sub_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.URLField(default=None),
        ),
    ]
